grails:
    profile: web
    codegen:
        defaultPackage: com.budjb.rabbitmq.test

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

rabbitmq:
    host: localhost
    port: 5672
    user: guest
    password: guest
    test:
        host: ${rabbitmq.host}
    connections:
      - name: connection1
        host: localhost
        username: guest
        password: guest
        virtualHost: test1.rabbitmq.budjb.com
        isDefault: true

      - name: connection2
        host: ${rabbitmq.host}
        username: ${rabbitmq.user}
        password: ${rabbitmq.password}
        virtualHost: test2.rabbitmq.budjb.com

    exchanges:
      - name: topic-exchange
        type: topic
        autoDelete: true

    queues:
      - name: message-context
        autoDelete: true
        connection: connection1

      - name: reporting
        autoDelete: true
        connection: connection1

      - name: sleeping
        autoDelete: true
        connection: connection1

      - name: string-test
        autoDelete: true
        connection: connection1

      - name: topic-queue-all
        autoDelete: true
        binding: '#'
        connection: connection1
        exchange: topic-exchange

      - name: topic-queue-subset
        autoDelete: true
        binding: 'com.budjb.#'
        connection: connection1
        exchange: topic-exchange

      - name: topic-queue-specific
        autoDelete: true
        binding: com.budjb.rabbitmq
        connection: connection1
        exchange: topic-exchange

      - name: connection2-queue
        autoDelete: true
        connection: connection2
